#!/usr/bin/env bun
// ---------------------------------------------------------------------------
// Atlas Knowledge Corpus — Deployment & Ingestion Script
//
// Usage:
//   bun run scripts/deploy-corpus.ts [--validate-only] [--ingest-only]
//
// This script:
//   1. Validates the corpus (structural + data integrity)
//   2. Generates the SQL ingestion payload
//   3. Can optionally push migrations via supabase CLI
//   4. Can optionally ingest via supabase SQL
//
// Requires: bun, supabase CLI (for push/ingest)
// ---------------------------------------------------------------------------

import { validateCorpus, getIngestionReport } from "../src/lib/knowledge/corpus/importer";
import {
  normalizeCorpusToKnowledgeItems,
  normalizeCorpusProvenance,
  getValidatedGraphEdges,
} from "../src/lib/knowledge/corpus/importer";
import { CORPUS_MANIFEST } from "../src/lib/knowledge/corpus/manifest";

const args = process.argv.slice(2);
const validateOnly = args.includes("--validate-only");
const ingestOnly = args.includes("--ingest-only");

async function main() {
  console.log("=" .repeat(70));
  console.log("ATLAS KNOWLEDGE CORPUS — DEPLOYMENT & INGESTION");
  console.log("=" .repeat(70));
  console.log();

  // ── Step 1: Validate corpus ──
  console.log("STEP 1: Validating corpus...");
  const validation = validateCorpus();
  const report = getIngestionReport(validation);

  console.log(`  Corpus: ${report.corpus} v${report.version}`);
  console.log(`  Release: ${report.releaseId}`);
  console.log(`  QC Status: ${report.qcStatus}`);
  console.log();
  console.log(`  Total records: ${report.totalRecords}`);
  console.log(`  Valid records: ${report.knowledgeItemsReady}`);
  console.log(`  Rejected: ${report.rejected}`);
  console.log(`  Duplicates: ${report.duplicates}`);
  console.log();
  console.log("  By category:");
  for (const [cat, count] of Object.entries(report.categoryCounts)) {
    console.log(`    ${cat}: ${count}`);
  }
  console.log();
  console.log(`  Provenance records: ${report.provenanceRecordsReady}`);
  console.log(`  Graph edges: ${report.graphEdgesReady}`);
  console.log(`  Orphan edges: ${report.orphanEdges}`);

  if (report.warnings.length > 0) {
    console.log();
    console.log("  Warnings:");
    for (const w of report.warnings) {
      console.log(`    ⚠️  ${w}`);
    }
  }

  if (report.errors.length > 0) {
    console.log();
    console.log("  ERRORS:");
    for (const e of report.errors) {
      console.log(`    ❌ ${e}`);
    }
    console.log();
    console.log("FAILED: Corpus validation errors must be fixed before ingestion.");
    process.exit(1);
  }

  console.log();
  console.log("  ✅ Corpus validation PASSED");
  console.log();

  if (validateOnly) {
    console.log("Validation complete (--validate-only mode). Exiting.");
    return;
  }

  // ── Step 2: Generate ingestion SQL ──
  console.log("STEP 2: Generating ingestion SQL...");

  const knowledge = normalizeCorpusToKnowledgeItems();
  const provenance = normalizeCorpusProvenance();
  const edges = getValidatedGraphEdges();

  // Convert to JSONB-compatible format for the RPC
  const knowledgeJson = JSON.stringify(
    knowledge.map((k) => ({
      title: k.title,
      statement: k.statement,
      interpretation: k.interpretation,
      knowledgeType: k.knowledgeType,
      sourceClassification: k.sourceClassification,
      industry: k.industry,
      jurisdiction: k.jurisdiction,
      confidence: k.confidence,
      status: k.status,
      isInference: k.isInference,
      tags: k.tags,
      sourceId: k.sourceId,
    })),
  );

  const provenanceJson = JSON.stringify(
    provenance.map((p) => ({
      sourceId: p.sourceId,
      sourceName: p.sourceName,
      organization: p.organization,
      authorityTier: p.authorityTier,
      sourceType: p.sourceType,
      canonicalUrl: p.canonicalUrl,
      status: p.status,
    })),
  );

  const edgesJson = JSON.stringify(
    edges.map((e) => ({
      sourceId: e.sourceId,
      targetId: e.targetId,
      relationship: e.relationship,
    })),
  );

  console.log(`  Knowledge items: ${knowledge.length}`);
  console.log(`  Provenance records: ${provenance.length}`);
  console.log(`  Graph edges: ${edges.length}`);
  console.log();

  // Write the SQL file
  const sqlPath = "supabase/seed_corpus.sql";
  const sql = \`-- Atlas Knowledge Corpus — Ingestion SQL
-- Generated by deploy-corpus.ts
-- Run: psql or supabase sql to execute
-- Idempotent: safe to run multiple times

SELECT public.industry_ingest_corpus(
  '\${knowledgeJson.replace(/'/g, "''")}'::jsonb,
  '\${provenanceJson.replace(/'/g, "''")}'::jsonb,
  '\${edgesJson.replace(/'/g, "''")}'::jsonb,
  '\${CORPUS_MANIFEST.version}'
);
\`;

  const fs = await import("fs");
  fs.writeFileSync(sqlPath, sql);
  console.log(\`  Written: \${sqlPath} (\${sql.length} bytes)\`);
  console.log();

  if (ingestOnly) {
    console.log("Ingestion SQL generated. Run manually:");
    console.log(\`  supabase sql --file \${sqlPath}\`);
    return;
  }

  // ── Step 3: Push migrations (if supabase CLI available) ──
  const { execSync } = await import("child_process");
  let hasSupabase = false;
  try {
    execSync("which supabase", { stdio: "pipe" });
    hasSupabase = true;
  } catch {
    // supabase CLI not available
  }

  if (hasSupabase) {
    console.log("STEP 3: Pushing migrations...");
    try {
      execSync("npx supabase db push", { stdio: "inherit", timeout: 120000 });
      console.log("  ✅ Migrations pushed successfully");
    } catch (e) {
      console.log("  ⚠️  Migration push had issues (check output above)");
      console.log("  Continuing with ingestion...");
    }
    console.log();

    console.log("STEP 4: Ingesting corpus...");
    try {
      execSync(\`npx supabase sql --file \${sqlPath}\`, { stdio: "inherit", timeout: 60000 });
      console.log("  ✅ Corpus ingested successfully");
    } catch (e) {
      console.log("  ⚠️  Ingestion had issues (check output above)");
    }
  } else {
    console.log("STEP 3-4: Supabase CLI not available in this environment.");
    console.log("  To complete deployment, run locally:");
    console.log("    npx supabase db push");
    console.log(\`    npx supabase sql --file \${sqlPath}\`);
  }

  console.log();
  console.log("=" .repeat(70));
  console.log("DEPLOYMENT SUMMARY");
  console.log("=" .repeat(70));
  console.log(\`  Migrations: \${hasSupabase ? "pushed (see above)" : "manual (run supabase db push)"}\`);
  console.log(\`  Ingestion SQL: \${sqlPath}\`);
  console.log(\`  Records to ingest: \${knowledge.length} knowledge + \${provenance.length} provenance + \${edges.length} edges\`);
  console.log();
}

main().catch((err) => {
  console.error("Deployment failed:", err);
  process.exit(1);
});
